package compaction

import (
	"bytes"
	"fmt"
	"io"
	"os"

	"github.com/silent-knight19/lattice/internal/binary"
	"github.com/silent-knight19/lattice/internal/errors"
	"github.com/silent-knight19/lattice/internal/sstable"
	"github.com/silent-knight19/lattice/internal/version"
)

const (
	// DefaultTargetPartitionSize defines the standard 2 MiB partition boundary
	// for compaction output SSTables (2 * 1024 * 1024 bytes).
	DefaultTargetPartitionSize uint64 = 2 * 1024 * 1024
)

// FileNumAllocator is a callback function that atomically allocates and returns
// the next unique sequential file number. It is compatible with engine.AllocateFileNum.
type FileNumAllocator func() (uint64, error)

// TombstoneSafetyChecker evaluates whether a tombstone record (OpTypeDelete) for a
// given UserKey can be safely dropped without risking ghost-key resurrection.
// It is implemented by *Compactor.
type TombstoneSafetyChecker interface {
	CanDropTombstone(userKey []byte, targetLevel int) bool
}

// TombstoneSafetyFunc is an adapter allowing the use of ordinary functions as TombstoneSafetyChecker.
type TombstoneSafetyFunc func(userKey []byte, targetLevel int) bool

// CanDropTombstone calls f(userKey, targetLevel).
func (f TombstoneSafetyFunc) CanDropTombstone(userKey []byte, targetLevel int) bool {
	return f(userKey, targetLevel)
}

// CompactionOutputConfig encapsulates all operational configuration options for
// generating physical SSTables from a compaction merge stream.
type CompactionOutputConfig struct {
	// DbDir is the directory path where finalized SSTables are published.
	DbDir string

	// TargetLevel is the LSM level targeted by the compaction (0 <= TargetLevel < NumLevels).
	TargetLevel int

	// TargetPartitionSize is the target maximum size of each output SSTable.
	// Defaults to DefaultTargetPartitionSize (2 MiB).
	TargetPartitionSize uint64

	// TargetBlockSize is the target data block size for each SSTable writer.
	// Defaults to sstable.TargetBlockSize (4096 bytes).
	TargetBlockSize int

	// CloseIterator indicates whether the generator should close the input iterator upon completion.
	CloseIterator bool

	// SkipValidation disables the post-finalization TableReader validation pass.
	// Defaults to false (validation is enabled).
	SkipValidation bool

	// TableWriterOptions provides custom options for SSTable construction.
	TableWriterOptions sstable.TableWriterOptions
}

// DefaultCompactionOutputConfig returns production defaults for CompactionOutputConfig.
func DefaultCompactionOutputConfig() CompactionOutputConfig {
	return CompactionOutputConfig{
		TargetPartitionSize: DefaultTargetPartitionSize,
		TargetBlockSize:     sstable.TargetBlockSize,
		CloseIterator:       false,
		SkipValidation:      false,
		TableWriterOptions:  sstable.DefaultTableWriterOptions(),
	}
}

// CompactionOutputOption defines functional options for Compactor.BuildOutput.
type CompactionOutputOption func(*CompactionOutputConfig)

// WithTargetPartitionSize configures a custom partition boundary in bytes.
func WithTargetPartitionSize(size uint64) CompactionOutputOption {
	return func(cfg *CompactionOutputConfig) {
		cfg.TargetPartitionSize = size
	}
}

// WithTargetBlockSize configures a custom SSTable data block size.
func WithTargetBlockSize(size int) CompactionOutputOption {
	return func(cfg *CompactionOutputConfig) {
		cfg.TargetBlockSize = size
	}
}

// WithCloseIterator specifies whether the input iterator should be closed automatically.
func WithCloseIterator(closeIter bool) CompactionOutputOption {
	return func(cfg *CompactionOutputConfig) {
		cfg.CloseIterator = closeIter
	}
}

// WithSkipValidation controls whether to skip post-write TableReader validation.
func WithSkipValidation(skip bool) CompactionOutputOption {
	return func(cfg *CompactionOutputConfig) {
		cfg.SkipValidation = skip
	}
}

// WithTableWriterOptions configures underlying SSTable TableWriterOptions.
func WithTableWriterOptions(opts sstable.TableWriterOptions) CompactionOutputOption {
	return func(cfg *CompactionOutputConfig) {
		cfg.TableWriterOptions = opts
	}
}

// CompactionOutputFile represents a single finalized, persisted SSTable generated by compaction.
type CompactionOutputFile struct {
	FileNum         uint64
	Level           int
	Path            string
	Meta            version.FileMetadata
	EntryCount      uint64
	TombstoneCount  uint64
	SmallestKey     []byte // encoded InternalKey
	LargestKey      []byte // encoded InternalKey
	SmallestUserKey []byte // raw UserKey
	LargestUserKey  []byte // raw UserKey
}

// FileMetadata returns the persistent version.FileMetadata descriptor for VersionSet edits.
func (f CompactionOutputFile) FileMetadata() version.FileMetadata {
	return f.Meta
}

// CompactionOutputStats records diagnostic metrics for a compaction output generation run.
type CompactionOutputStats struct {
	InputRecords       uint64
	WrittenRecords     uint64
	OmittedTombstones  uint64
	RetainedTombstones uint64
	TotalOutputBytes   uint64
	OutputFilesCount   int
}

// CompactionOutput groups all finalized output SSTables and summary statistics.
type CompactionOutput struct {
	Files []CompactionOutputFile
	Stats CompactionOutputStats
}

// FileMetadatas returns a slice of all version.FileMetadata descriptors in the output.
func (o *CompactionOutput) FileMetadatas() []version.FileMetadata {
	if o == nil || len(o.Files) == 0 {
		return nil
	}
	out := make([]version.FileMetadata, len(o.Files))
	for i, f := range o.Files {
		out[i] = f.Meta
	}
	return out
}

// BuildCompactionOutput consumes a pre-sorted compaction merge iterator, applies tombstone
// purge safety decisions, partitions records across ~2 MiB SSTable boundaries, generates
// immutable SSTables via sstable.TableWriter, and returns finalized file metadata.
//
// Invariants & Operational Semantics:
//  1. Ordering Invariant: Records are consumed and written in strictly increasing canonical order
//     (UserKey ASC, SeqNum DESC, OpType DESC). The output layer does not reorder records.
//  2. Tombstone Purge Invariant: Tombstones (OpTypeDelete) are physically omitted IF AND ONLY IF
//     safety.CanDropTombstone(key.UserKey, cfg.TargetLevel) reports true. All other records are preserved.
//  3. 2 MiB Partitioning & Oversized Record Policy:
//     - Bounded partitioning targets TargetPartitionSize (default 2 MiB).
//     - If adding the next record would cause the current non-empty table to exceed the target size,
//     the current table is finalized first.
//     - Oversized Single Record: If a single record exceeds TargetPartitionSize by itself, it is
//     written into an empty table and finalized immediately upon the next record, ensuring
//     continuous forward progress with zero infinite loops.
//  4. Atomic Record Boundary: Single records are never split across files.
//  5. Empty Output Contract: If the input stream is empty, or all records are safely dropped tombstones,
//     zero SSTables are generated and an empty output slice is returned.
//  6. Fail-Closed Durability: If an error occurs at any point during writing, finalization, or
//     validation, all partially written temporary staging files and finalized files created during
//     this run are unlinked, and the error is returned immediately.
//  7. Visibility Boundary: Finalized output SSTables are physically durable on disk but are NOT yet
//     visible to readers or the active VersionSet until committed via VersionEdit in P08-S03-M02.
func BuildCompactionOutput(
	iter sstable.Iterator,
	safety TombstoneSafetyChecker,
	alloc FileNumAllocator,
	cfg CompactionOutputConfig,
) (*CompactionOutput, error) {
	if iter == nil {
		return nil, errors.ErrNilReceiver
	}
	if safety == nil {
		return nil, fmt.Errorf("compaction: tombstone safety checker cannot be nil")
	}
	if alloc == nil {
		return nil, fmt.Errorf("compaction: file number allocator cannot be nil")
	}
	if cfg.DbDir == "" {
		return nil, fmt.Errorf("compaction: database directory cannot be empty")
	}
	if cfg.TargetLevel < 0 || cfg.TargetLevel >= version.NumLevels {
		return nil, fmt.Errorf("compaction: invalid target level %d (must be in range 0..%d)", cfg.TargetLevel, version.NumLevels-1)
	}
	if cfg.TargetPartitionSize == 0 {
		cfg.TargetPartitionSize = DefaultTargetPartitionSize
	}
	if cfg.TargetBlockSize <= 0 {
		cfg.TargetBlockSize = sstable.TargetBlockSize
	}

	if cfg.CloseIterator {
		defer func() {
			if c, ok := iter.(io.Closer); ok {
				_ = c.Close()
			}
		}()
	}

	var (
		currentWriter         *sstable.TableWriter
		currentFileNum        uint64
		currentFilePath       string
		currentTombstoneCount uint64
		finalizedFiles        []CompactionOutputFile
		createdPaths          []string
		stats                 CompactionOutputStats
	)

	// cleanupOnError unlinks all files created in this failed run and closes open writers.
	cleanupOnError := func() {
		if currentWriter != nil {
			_ = currentWriter.Close()
			currentWriter = nil
		}
		for _, p := range createdPaths {
			_ = os.Remove(p)
		}
		finalizedFiles = nil
	}

	// startNewWriter allocates a unique file number and initializes an atomic TableWriter.
	startNewWriter := func() error {
		fileNum, err := alloc()
		if err != nil {
			return fmt.Errorf("compaction: allocator failed: %w", err)
		}
		if fileNum == 0 {
			return fmt.Errorf("compaction: allocator returned invalid file number 0")
		}

		filePath := version.TablePath(cfg.DbDir, fileNum)
		writerOpts := cfg.TableWriterOptions
		if writerOpts.TargetBlockSize <= 0 {
			writerOpts.TargetBlockSize = cfg.TargetBlockSize
		}

		w, err := sstable.NewTableWriter(filePath, writerOpts)
		if err != nil {
			return fmt.Errorf("compaction: failed to create table writer for %s: %w", filePath, err)
		}

		currentWriter = w
		currentFileNum = fileNum
		currentFilePath = filePath
		currentTombstoneCount = 0
		return nil
	}

	// finalizeCurrentWriter finishes the active TableWriter, validates it, and records metadata.
	finalizeCurrentWriter := func() error {
		if currentWriter == nil || currentWriter.EntryCount() == 0 {
			if currentWriter != nil {
				_ = currentWriter.Close()
				currentWriter = nil
			}
			return nil
		}

		sstMeta, err := currentWriter.Finish()
		if err != nil {
			return fmt.Errorf("compaction: failed to finalize table %s: %w", currentFilePath, err)
		}
		createdPaths = append(createdPaths, currentFilePath)

		fMeta := version.NewFileMetadataFromSSTable(currentFileNum, sstMeta)

		// Physical validation via TableReader
		if !cfg.SkipValidation {
			if err := ValidateSSTableOutput(currentFilePath, fMeta); err != nil {
				return fmt.Errorf("compaction: validation failed for table %s: %w", currentFilePath, err)
			}
		}

		minIK, err := binary.DecodeInternalKey(sstMeta.SmallestKey)
		if err != nil {
			return fmt.Errorf("compaction: failed to decode smallest internal key: %w", err)
		}
		maxIK, err := binary.DecodeInternalKey(sstMeta.LargestKey)
		if err != nil {
			return fmt.Errorf("compaction: failed to decode largest internal key: %w", err)
		}

		outTable := CompactionOutputFile{
			FileNum:         currentFileNum,
			Level:           cfg.TargetLevel,
			Path:            currentFilePath,
			Meta:            fMeta,
			EntryCount:      sstMeta.EntryCount,
			TombstoneCount:  currentTombstoneCount,
			SmallestKey:     bytes.Clone(sstMeta.SmallestKey),
			LargestKey:      bytes.Clone(sstMeta.LargestKey),
			SmallestUserKey: bytes.Clone(minIK.UserKey),
			LargestUserKey:  bytes.Clone(maxIK.UserKey),
		}

		finalizedFiles = append(finalizedFiles, outTable)
		stats.TotalOutputBytes += fMeta.FileSize
		stats.OutputFilesCount++

		currentWriter = nil
		currentFileNum = 0
		currentFilePath = ""
		currentTombstoneCount = 0
		return nil
	}

	// Prime the iterator if not yet positioned
	if !iter.Valid() {
		if !iter.Next() {
			if er, ok := iter.(interface{ Err() error }); ok {
				if err := er.Err(); err != nil {
					return nil, fmt.Errorf("compaction: iterator error: %w", err)
				}
			}
			// Clean empty input stream: produce 0 output SSTables
			return &CompactionOutput{
				Files: nil,
				Stats: stats,
			}, nil
		}
	}

	// Consume the merged logical stream
	for iter.Valid() {
		stats.InputRecords++
		key := iter.Key()
		val := iter.Value()

		// Validate key and value integrity upfront
		if err := binary.ValidateKey(key.UserKey); err != nil {
			cleanupOnError()
			return nil, fmt.Errorf("compaction: invalid user key: %w", err)
		}
		if err := key.OpType.Validate(); err != nil {
			cleanupOnError()
			return nil, fmt.Errorf("compaction: invalid operation type: %w", err)
		}
		if err := binary.ValidateValue(val); err != nil {
			cleanupOnError()
			return nil, fmt.Errorf("compaction: invalid value: %w", err)
		}

		// Tombstone Purge Safety Evaluation:
		// CRITICAL DOMAIN DISTINCTION:
		// CanDropTombstone operates strictly on UserKey identity (whether any older revision
		// exists in deeper levels). In contrast, output ordering and writing operate on
		// InternalKey identity (UserKey, SeqNum, OpType). Passing internal key bytes
		// would corrupt user-key range lookups and cause false negatives.
		if key.OpType == binary.OpTypeDelete {
			if safety.CanDropTombstone(key.UserKey, cfg.TargetLevel) {
				// Provably safe to drop: physically omit from output
				stats.OmittedTombstones++
				if !iter.Next() {
					break
				}
				continue
			}
			// Unsafe to drop: must be retained in output
			stats.RetainedTombstones++
		}

		// Partition Boundary Check:
		// If current table already contains records, check if adding this record would cause
		// the table's estimated size to exceed TargetPartitionSize.
		if currentWriter != nil && currentWriter.EntryCount() > 0 {
			recSize := uint64(len(key.UserKey) + 8 + len(val) + 16)
			if currentWriter.EstimatedSize() >= cfg.TargetPartitionSize ||
				(currentWriter.EstimatedSize()+recSize > cfg.TargetPartitionSize) {
				if err := finalizeCurrentWriter(); err != nil {
					cleanupOnError()
					return nil, err
				}
			}
		}

		// Start fresh writer if needed
		if currentWriter == nil {
			if err := startNewWriter(); err != nil {
				cleanupOnError()
				return nil, err
			}
		}

		// Append record to current SSTable
		var writeVal []byte
		if key.OpType == binary.OpTypeDelete {
			writeVal = nil
			currentTombstoneCount++
		} else {
			writeVal = val
		}

		if err := currentWriter.Add(key, writeVal); err != nil {
			cleanupOnError()
			return nil, fmt.Errorf("compaction: failed to append record to %s: %w", currentFilePath, err)
		}
		stats.WrittenRecords++

		if !iter.Next() {
			break
		}
	}

	// Verify iterator ended cleanly (clean EOF vs corruption)
	if er, ok := iter.(interface{ Err() error }); ok {
		if err := er.Err(); err != nil {
			cleanupOnError()
			return nil, fmt.Errorf("compaction: iterator error: %w", err)
		}
	}

	// Finalize remaining table if non-empty
	if currentWriter != nil && currentWriter.EntryCount() > 0 {
		if err := finalizeCurrentWriter(); err != nil {
			cleanupOnError()
			return nil, err
		}
	} else if currentWriter != nil {
		_ = currentWriter.Close()
		currentWriter = nil
	}

	return &CompactionOutput{
		Files: finalizedFiles,
		Stats: stats,
	}, nil
}

// BuildOutput executes compaction output generation using the Compactor's pinned Version
// snapshot to evaluate tombstone safety decisions against the CompactionPlan's TargetLevel.
func (c *Compactor) BuildOutput(
	iter sstable.Iterator,
	plan *CompactionPlan,
	dbDir string,
	alloc FileNumAllocator,
	opts ...CompactionOutputOption,
) (*CompactionOutput, error) {
	if c == nil {
		return nil, errors.ErrNilReceiver
	}
	c.mu.RLock()
	closed := c.closed
	c.mu.RUnlock()
	if closed {
		return nil, fmt.Errorf("compaction: compactor is closed")
	}
	if plan == nil {
		return nil, fmt.Errorf("compaction: compaction plan cannot be nil")
	}

	cfg := DefaultCompactionOutputConfig()
	cfg.DbDir = dbDir
	cfg.TargetLevel = plan.TargetLevel()

	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}

	return BuildCompactionOutput(iter, c, alloc, cfg)
}

// ValidateSSTableOutput performs strict physical and logical validation on a finalized SSTable file.
// It verifies:
//  1. Physical regular file existence and exact size match against FileMetadata.FileSize.
//  2. TableReader initialization (footer, index block, meta-index block parsing).
//  3. Full record iteration verifying block CRC32 checksums, strictly canonical key order,
//     and exact match of SmallestKey / LargestKey bounds.
func ValidateSSTableOutput(path string, meta version.FileMetadata) error {
	fi, err := os.Lstat(path)
	if err != nil {
		return fmt.Errorf("sstable lstat failed: %w", err)
	}
	if !fi.Mode().IsRegular() {
		return fmt.Errorf("sstable path %q is not a regular file", path)
	}
	// #nosec G115 -- guarded by fi.Size() >= 0
	if fi.Size() < 0 || uint64(fi.Size()) != meta.FileSize {
		return fmt.Errorf("sstable %q physical size %d does not match metadata size %d", path, fi.Size(), meta.FileSize)
	}

	reader, err := sstable.NewTableReader(path)
	if err != nil {
		return fmt.Errorf("sstable reopen failed: %w", err)
	}
	defer func() { _ = reader.Close() }()

	// #nosec G115 -- guarded by reader.FileSize() >= 0
	if reader.FileSize() < 0 || uint64(reader.FileSize()) != meta.FileSize {
		return fmt.Errorf("sstable %q reader reported size %d does not match metadata size %d", path, reader.FileSize(), meta.FileSize)
	}

	it, err := reader.NewIterator()
	if err != nil {
		return fmt.Errorf("sstable iterator creation failed: %w", err)
	}
	defer func() { _ = it.Close() }()

	var (
		count    uint64
		hasPrev  bool
		prevKey  binary.InternalKey
		firstKey binary.InternalKey
		lastKey  binary.InternalKey
	)

	for it.Next() {
		currKey := it.Key()
		if hasPrev {
			if binary.CompareInternalKey(prevKey, currKey) >= 0 {
				return fmt.Errorf("sstable %q key out of canonical order: prev >= curr", path)
			}
		} else {
			firstKey = currKey.Clone()
			hasPrev = true
		}
		lastKey = currKey.Clone()
		prevKey = currKey.Clone()
		count++
	}

	if err := it.Err(); err != nil {
		return fmt.Errorf("sstable iteration failed with error: %w", err)
	}

	if count == 0 {
		return fmt.Errorf("sstable %q has 0 records; empty SSTables are invalid", path)
	}

	firstEncoded := binary.AppendInternalKey(nil, firstKey)
	if !bytes.Equal(firstEncoded, meta.SmallestKey) {
		return fmt.Errorf("sstable %q smallest key mismatch: got %x, expected %x", path, firstEncoded, meta.SmallestKey)
	}

	lastEncoded := binary.AppendInternalKey(nil, lastKey)
	if !bytes.Equal(lastEncoded, meta.LargestKey) {
		return fmt.Errorf("sstable %q largest key mismatch: got %x, expected %x", path, lastEncoded, meta.LargestKey)
	}

	return nil
}
