package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/silent-knight19/lattice/internal/errors"
)

// CleanOrphanReport summarizes the diagnostic outcome of an orphaned temporary file cleanup pass.
type CleanOrphanReport struct {
	// CandidatesFound is the total count of safe orphan temporary files detected.
	CandidatesFound int

	// FilesCleaned is the count of orphan temporary files successfully unlinked.
	FilesCleaned int

	// Failures maps candidate relative filename to the specific error encountered during deletion or inspection.
	Failures map[string]error

	// DirectorySyncFailed indicates that hardware synchronization of the parent directory failed following unlinking.
	DirectorySyncFailed bool

	// SyncError records the underlying error encountered during parent directory synchronization.
	SyncError error
}

// Error formats any deletion or directory synchronization failures encountered into an aggregate error message.
// Returns nil if no failures occurred.
func (r CleanOrphanReport) Error() error {
	if len(r.Failures) == 0 && !r.DirectorySyncFailed {
		return nil
	}
	if len(r.Failures) == 0 && r.DirectorySyncFailed {
		return fmt.Errorf("directory synchronization failed: %w", r.SyncError)
	}
	var parts []string
	if len(r.Failures) > 0 {
		var errMsgs []string
		for name, err := range r.Failures {
			errMsgs = append(errMsgs, fmt.Sprintf("%s: %v", name, err))
		}
		parts = append(parts, fmt.Sprintf("clean orphaned files encountered %d failure(s): %s", len(r.Failures), strings.Join(errMsgs, "; ")))
	}
	if r.DirectorySyncFailed {
		parts = append(parts, fmt.Sprintf("directory synchronization failed: %v", r.SyncError))
	}
	return fmt.Errorf("%s", strings.Join(parts, "; "))
}

// IsOrphanStagingFile reports whether a directory entry name strictly conforms to the
// TableWriter temporary staging file grammar: ".tmp_<name>.sst_<random>".
//
// Invariants (P07-S02-M02-INV-01):
//  1. Must start with exact prefix ".tmp_".
//  2. Must contain ".sst_".
//  3. The base name between ".tmp_" and ".sst_" must be non-empty and must not contain
//     directory separators ('/', '\'), null bytes ('\x00'), or directory traversals (".", "..").
//  4. The suffix after ".sst_" is the random string generated by os.CreateTemp and must be
//     non-empty containing only safe alphanumeric, hyphen, or underscore characters.
//  5. Explicitly rejects persistent files: "CURRENT", "CURRENT.tmp", "MANIFEST-*", "*.sst", "wal".
func IsOrphanStagingFile(name string) bool {
	// 1. Strict prefix check
	if !strings.HasPrefix(name, ".tmp_") {
		return false
	}

	// 2. Reject directory traversal or path separators in entry name
	if strings.ContainsAny(name, "/\\\x00") {
		return false
	}

	// 3. Extract remainder after ".tmp_"
	rest := name[len(".tmp_"):]

	// 4. Must contain ".sst_"
	sstIdx := strings.Index(rest, ".sst_")
	if sstIdx <= 0 {
		// Must have at least 1 character for base name before ".sst_"
		return false
	}

	// 5. Validate base name before ".sst_"
	baseName := rest[:sstIdx]
	if baseName == "." || baseName == ".." {
		return false
	}

	// 6. Validate random suffix after ".sst_"
	suffix := rest[sstIdx+len(".sst_"):]
	if len(suffix) == 0 {
		return false
	}
	for i := 0; i < len(suffix); i++ {
		if !isValidSuffixChar(suffix[i]) {
			return false
		}
	}

	return true
}

func isValidSuffixChar(c byte) bool {
	return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '-' || c == '_'
}

// CleanOrphanedFilesDir scans the specified database directory and removes unreferenced
// crash-window temporary staging files left behind by interrupted TableWriter flushes or writes.
//
// Operational Contract & Invariants:
//   - P07-S02-M02-INV-01: Only files matching IsOrphanStagingFile are considered.
//   - P07-S02-M02-INV-02: Persistent files (CURRENT, MANIFEST, .sst, WAL) are never candidates.
//   - P07-S02-M02-INV-03: Symlink candidates are NEVER followed or deleted; targets are preserved.
//   - P07-S02-M02-INV-04: Directory candidates are NEVER recursively removed.
//   - P07-S02-M02-INV-05: Deletion is confined strictly to direct children of dbPath.
//   - P07-S02-M02-INV-06: Live database files remain 100% byte-identical.
//   - P07-S02-M02-INV-07: Cleanup is idempotent.
//   - P07-S02-M02-INV-08: Deletion failures are captured explicitly in CleanOrphanReport.
//   - P07-S02-M02-INV-09: Directory descriptor pinning prevents TOCTOU directory swaps.
//   - P07-S02-M02-INV-10: Files are unlinked without altering contents.
//   - P07-S02-M02-INV-11: Unknown or ambiguous files (.tmp, backup.tmp) are preserved.
//   - P07-S02-M02-INV-12: Subdirectories are never scanned or deleted.
func CleanOrphanedFilesDir(dbPath string) (CleanOrphanReport, error) {
	report := CleanOrphanReport{
		Failures: make(map[string]error),
	}

	if dbPath == "" {
		return report, fmt.Errorf("%w: dbPath cannot be empty", os.ErrInvalid)
	}

	cleanDBPath := filepath.Clean(dbPath)

	// Step 1: Pre-open inspection and parent directory pinning
	dirInfo, err := os.Lstat(cleanDBPath)
	if err != nil {
		if os.IsNotExist(err) {
			// Directory does not exist: nothing to clean
			return report, nil
		}
		return report, fmt.Errorf("cleaner: failed to inspect db directory %s: %w", cleanDBPath, err)
	}
	if dirInfo.Mode()&os.ModeSymlink != 0 {
		return report, fmt.Errorf("%w: db directory %s cannot be a symbolic link", os.ErrInvalid, cleanDBPath)
	}
	if !dirInfo.IsDir() {
		return report, &errors.NotADirectoryError{Path: cleanDBPath, Mode: dirInfo.Mode()}
	}

	// Open descriptor for pinned directory inspection
	dirFile, err := os.Open(cleanDBPath)
	if err != nil {
		return report, fmt.Errorf("cleaner: failed to open db directory %s: %w", cleanDBPath, err)
	}
	defer func() { _ = dirFile.Close() }()

	// Post-open verification: prove descriptor matches disk inode
	dirStat, err := dirFile.Stat()
	if err != nil {
		return report, fmt.Errorf("cleaner: failed to stat open db directory %s: %w", cleanDBPath, err)
	}
	if !os.SameFile(dirInfo, dirStat) {
		return report, errors.ErrParentDirectorySwapped
	}

	// Step 2: Read direct directory entries (bounded non-recursive scan)
	entries, err := dirFile.ReadDir(-1)
	if err != nil {
		return report, fmt.Errorf("cleaner: failed to read db directory %s: %w", cleanDBPath, err)
	}

	// Step 3: Iterate direct entries and apply conservative allowlist filter
	for _, entry := range entries {
		name := entry.Name()

		// Allowlist check: candidate must strictly conform to staging grammar
		if !IsOrphanStagingFile(name) {
			continue
		}

		// Containment check: candidate must be a direct child within cleanDBPath
		candidatePath := filepath.Clean(filepath.Join(cleanDBPath, name))
		if filepath.Dir(candidatePath) != cleanDBPath || filepath.Base(candidatePath) != name {
			continue
		}

		report.CandidatesFound++

		// Inspect candidate via Lstat to prevent following symlinks (INV-03)
		candInfo, lstatErr := os.Lstat(candidatePath)
		if lstatErr != nil {
			if os.IsNotExist(lstatErr) {
				// File was removed concurrently or already absent
				continue
			}
			report.Failures[name] = lstatErr
			continue
		}

		// Symlink Defense: Never follow, never unlink through symlink, never touch victim (INV-03)
		if candInfo.Mode()&os.ModeSymlink != 0 {
			report.Failures[name] = fmt.Errorf("security violation: candidate %s is a symlink (refusing to follow or unlink)", name)
			continue
		}

		// Directory Defense: Never recursively delete directories masquerading as temp files (INV-04, INV-12)
		if candInfo.IsDir() {
			report.Failures[name] = fmt.Errorf("security violation: candidate %s is a directory (refusing recursive deletion)", name)
			continue
		}

		// Special Object Defense: Reject FIFOs, sockets, character/block devices
		if !candInfo.Mode().IsRegular() {
			report.Failures[name] = fmt.Errorf("security violation: candidate %s is not a regular file (mode: %s)", name, candInfo.Mode())
			continue
		}

		// Step 4: Safely unlink validated regular file candidate (INV-05, INV-10)
		// unlinkAt operates strictly anchored to the pinned directory file descriptor (SEC-P07-02).
		if removeErr := unlinkAt(dirFile, name); removeErr != nil {
			if !os.IsNotExist(removeErr) {
				report.Failures[name] = removeErr
				continue
			}
			report.FilesCleaned++
		} else {
			report.FilesCleaned++
		}
	}

	// Step 5: Directory durability sync if mutations occurred (SEC-P07-06)
	if report.FilesCleaned > 0 {
		if syncErr := cleanerSyncDirFn(dirFile); syncErr != nil {
			report.DirectorySyncFailed = true
			report.SyncError = syncErr
		}
	}

	return report, report.Error()
}

var cleanerSyncDirFn = func(f *os.File) error {
	return f.Sync()
}

// SetCleanerSyncDirFnForTesting overrides cleanerSyncDirFn for testing directory sync failures.
func SetCleanerSyncDirFnForTesting(fn func(*os.File) error) func() {
	prev := cleanerSyncDirFn
	cleanerSyncDirFn = fn
	return func() {
		cleanerSyncDirFn = prev
	}
}

// CleanOrphanedFiles scans the database directory and removes unreferenced crash-window
// temporary staging files left behind by interrupted TableWriter writes or flushes.
// It acquires the engine mutex to guarantee mutual exclusion with concurrent operations.
func (e *Engine) CleanOrphanedFiles() error {
	_, err := e.CleanOrphanedFilesWithReport()
	return err
}

// CleanOrphanedFilesWithReport scans the database directory, removes orphan temporary files,
// and returns a structured CleanOrphanReport containing detailed diagnostic counts.
func (e *Engine) CleanOrphanedFilesWithReport() (CleanOrphanReport, error) {
	if e == nil {
		return CleanOrphanReport{}, errors.ErrNilReceiver
	}
	if e.closed.Load() {
		return CleanOrphanReport{}, errors.ErrWriterClosed
	}

	e.mu.Lock()
	defer e.mu.Unlock()

	dbPath := e.dbPath
	if dbPath == "" {
		return CleanOrphanReport{}, fmt.Errorf("%w: engine dbPath cannot be empty", os.ErrInvalid)
	}

	return CleanOrphanedFilesDir(dbPath)
}
